/* sw.js — generated by build-site.js. Do not hand-edit; edit tools/sw.tpl.js.
 *
 * Two caches, one version:
 *   tara-shell-<v>   the shell: index.html, the hashed css/js, manifest, icons.
 *                    Precached on install so the app works offline after one visit.
 *   tara-assets-<v>  assets/*.gz payloads, cached on first use.
 *
 * Strategy:
 *   navigations + index.html   network-first, fall back to the cached shell
 *   hashed assets (assets/, css/, js/, icons/)  cache-first — the name changes
 *                              when the bytes do, so a hit is always correct
 *   anything else same-origin  cache-first, then network
 *   cross-origin               not intercepted at all. The packs and demos pull
 *                              highlight.js and three.js from cdnjs/jsdelivr,
 *                              web fonts from fonts.googleapis.com, and the
 *                              sprint pulls pyodide from jsdelivr. Those are
 *                              third-party, versioned and large; the browser's
 *                              own HTTP cache handles them and a failed one must
 *                              fail visibly rather than be masked by the worker.
 */

const VERSION = '390c1b7a9c81';
const SHELL_CACHE = 'tara-shell-' + VERSION;
const ASSET_CACHE = 'tara-assets-' + VERSION;

/* Relative to the worker's own URL, so the site works from any subpath
   (https://<owner>.github.io/<repo>/). */
const SHELL_FILES = [
  "./",
  "index.html",
  "manifest.json",
  "css/shell.04c2b6dbb6.css",
  "js/app.fcdf6dd7f4.js",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-192.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg"
];

const SCOPE = new URL('./', self.location.href);

function isImmutable(url) {
  const p = url.pathname.slice(SCOPE.pathname.length);
  return /^assets\//.test(p) || /^icons\//.test(p) ||
         /^css\/[^/]+\.[0-9a-f]{6,}\.css$/.test(p) ||
         /^js\/[^/]+\.[0-9a-f]{6,}\.js$/.test(p);
}

function isShellDoc(url) {
  const p = url.pathname;
  return p === SCOPE.pathname || p === SCOPE.pathname + 'index.html';
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    /* addAll is all-or-nothing; one 404 would leave the app with no offline
       shell at all, so each file is added on its own and failures are logged. */
    await Promise.all(SHELL_FILES.map(async (f) => {
      const url = new URL(f, SCOPE).href;
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (res.ok) await cache.put(url, res.clone());
        else console.warn('[sw] precache skipped', f, res.status);
      } catch (e) { console.warn('[sw] precache failed', f, e && e.message); }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map((k) => {
      if (k === SHELL_CACHE || k === ASSET_CACHE) return null;
      if (!/^tara-(shell|assets)-/.test(k)) return null;   // never touch someone else's cache
      return caches.delete(k);
    }));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // third-party: hands off
  if (!url.pathname.startsWith(SCOPE.pathname)) return;   // outside our scope

  /* The shell document: always try the network so a redeploy lands, but never
     fail — a cached shell is what makes the app work offline. */
  /* Intuition films (intuition/*): their own pages, edited often, so always
     network-first and cached under their own URL, never as the shell. */
  if (/\/intuition\//.test(url.pathname.slice(SCOPE.pathname.length - 1))) {
    event.respondWith((async () => {
      const cache = await caches.open(SHELL_CACHE);
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      } catch (e) {
        const hit = await cache.match(req);
        if (hit) return hit;
        throw e;
      }
    })());
    return;
  }

  if (req.mode === 'navigate' || isShellDoc(url)) {
    event.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res && res.ok) {
          const cache = await caches.open(SHELL_CACHE);
          cache.put(new URL('index.html', SCOPE).href, res.clone());
        }
        return res;
      } catch (e) {
        const cache = await caches.open(SHELL_CACHE);
        return (await cache.match(new URL('index.html', SCOPE).href)) ||
               (await cache.match(new URL('./', SCOPE).href)) ||
               new Response('Offline and no cached shell.', { status: 503, headers: { 'Content-Type': 'text/plain' } });
      }
    })());
    return;
  }

  const immutable = isImmutable(url);
  event.respondWith((async () => {
    const cacheName = /\/assets\//.test(url.pathname) ? ASSET_CACHE : SHELL_CACHE;
    const cache = await caches.open(cacheName);
    const hit = await cache.match(req, { ignoreSearch: false });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.ok && (immutable || res.type === 'basic')) cache.put(req, res.clone());
      return res;
    } catch (e) {
      const any = await caches.match(req);
      if (any) return any;
      throw e;
    }
  })());
});
